const campsiteTypes = {
  FULL_HOOKUP: "FULL_HOOKUP",
  WATER_ELECTRIC_SEWER: "WATER_ELECTRIC_SEWER",
  RIVERFRONT_WATER_ELECTRIC: "RIVERFRONT_WATER_ELECTRIC",
  WATER_ELECTRIC: "WATER_ELECTRIC",
  NO_HOOKUP: "NO_HOOKUP"
};

export default campsiteTypes;